apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  tssc/gitops: ep0x63sbz-nodejs 
  janus-idp.io/tekton: ep0x63sbz-nodejs
  backstage.io/kubernetes-id: ep0x63sbz-nodejs
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: ep0x63sbz-nodejs
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml