apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: ep0x63sbz-nodejs
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: ep0x63sbz-nodejs 
  name: ep0x63sbz-nodejs
spec:
  ports:
  - port: 3001 
    targetPort: 3001 
  selector:
    app.kubernetes.io/instance: ep0x63sbz-nodejs 
